version: '3.8'

services:
  football-qa-bot:
    build: .
    container_name: football-qa-bot
    volumes:
      # 로그, 데이터베이스, 캐시 등의 영구 데이터를 위한 볼륨 마운트
      - ./logs:/app/logs
      - ./database:/app/database
      - ./cache:/app/cache
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - LOG_LEVEL=INFO
      - LOG_DIR=logs
    command: python main.py --web --port 8000
    restart: unless-stopped
